language: node_js

python:
  - "3.6"

node_js:
  - 'node'
  - 'lts/*'

sudo: false

install:
  - npm install
  - pip install -r requirements.txt

script:
  - npm run build
  - npm run test
  - nosetests mnist/test -v
